#! /bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket server"
        start-stop-daemon -S -n aesdsocket -a /usr/bin/server/aesdsocket -b --make-pidfile --pidfile /var/run/aesdsocket.pid -- -d
        ;;
    stop)
        echo "Stopping aesdsocket server"
        start-stop-daemon -K --pidfile /var/run/aesdsocket.pid --retry 5 --remove-pidfile
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0